version: "3.1"
services:

  mysql:
    container_name: mysql-server
    restart: always
    image: mysql
    expose:
      - "3306"
    ports:
      - "3307:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    env_file:
      - variables.env

  app:
    container_name: phalcon-server
    build: .
    restart: always
    ports:
      - "8181:80"
    volumes:
      - ./phpconfig:/usr/local/etc/php
      - ./app:/var/www/app
      - ./public:/var/www/html
    depends_on:
      - mysql
