<?php echo \Phalcon\Tag::form('user/auth') ?>
<div class="row">

    <div class="col-3 offset-5">
        <div class="row">
            <div class="col">
                <?php print_r($this->flash->output()); ?>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <form action="/user/auth" method="post">
                    <input type='hidden' name='<?php echo $this->security->getTokenKey() ?>'
                           value='<?php echo $this->security->getToken() ?>'/>
                    <div class="form-group">
                        <label for="email">Email address</label>
                        <?php echo $form->render('email') ?>
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <?php echo $form->render('password') ?>
                    </div>

                    <div class="form-row" style="margin-top: 20px">
                        <div class="col">
                            <a class="btn btn-danger" href="/user/registration">Sign Up</a>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>