<div class="row" >
    <div class="col-3 offset-5">
        <div class="row">
            <div class="col">
                <?php print_r($this->flash->output()); ?>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <form action="/user/registration" method="post">
                    <div class="form-row">
                        <div class="col">
                            <label for="name">Name</label>
                            <?php echo $form->render('name') ?>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col">
                            <label for="email">Email address</label>
                            <?php echo $form->render('email') ?>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col">
                            <label for="password">Password</label>
                            <?php echo $form->render('password') ?>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col">
                            <label for="confirmPassword">Confirm Password</label>
                            <?php echo $form->render('confirmPassword') ?>
                        </div>
                    </div>
                    <div class="form-row" style="margin-top: 20px">
                        <div class="col">
                            <a class="btn btn-danger" href="/user/auth">Sign In</a>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>

    </div>
</div>